### ISSUE TITLE
Tablerulesets can be specified from a YAML source

### ISSUE THREAD

**Issue by miraculixx** [miraculixx/pyrules#14]
Current, tablerulesets are defined using a python-dict notation:

```
manyrules = TableRuleset([
  { 'if': ['not weekend'],
    'then' : ['fare * 1'],
    'target' : ['fare'],
  },
  { 'if': ['not sunday'],
    'then' : ['fare * 1.5'],
    'target' : ['fare'],
  }
])
```

The goal is to specify this in YAML:

```yml
ruleset: <name>
- rule: <name>
    if:  
    - not weekend
    then:
    -  fare * 1
    target:
    -  fare 
[...]
```

Basically the structures should match, if they don't, the JSON structure should be the one that counts, change the yml structure accordingly.

### Expected behavior
1. Tablerulesets can be instantiated by a YML source. In particular, if the class definition contains a __specs__ attribute (see #13), the tableruleset should take this as if it were specified as a dict in `__init__`.

**Comment by antisvin** [comment]
Rules inside ruleset don't have names, so there's no use for "- rule: <name>". Same goes for for ruleset names (unless we plan to generate multiple TableRuleset's from a single YAML file, which I don't think is the case). So an example would be:

```
- if:
    - not weekend
  then:
    - fare * 1
  target:
    - fare
- if:
    - not sunday
  then:
    - fare * 1.5
  target:
    - fare
```

This gives the following python structure:

```
[{'if': ['not weekend'], 'target': ['fare'], 'then': ['fare * 1']},
 {'if': ['not sunday'], 'target': ['fare'], 'then': ['fare * 1.5']}]
```
